// proto/resume.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/resume.proto

package resume

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resume represents a candidate's resume
type Resume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	FileUrl       string                 `protobuf:"bytes,6,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	ParsedData    []byte                 `protobuf:"bytes,7,opt,name=parsed_data,json=parsedData,proto3" json:"parsed_data,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_proto_resume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{0}
}

func (x *Resume) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resume) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Resume) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Resume) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Resume) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *Resume) GetParsedData() []byte {
	if x != nil {
		return x.ParsedData
	}
	return nil
}

func (x *Resume) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Resume) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Resume) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// GetResumeRequest
type GetResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResumeRequest) Reset() {
	*x = GetResumeRequest{}
	mi := &file_proto_resume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumeRequest) ProtoMessage() {}

func (x *GetResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumeRequest.ProtoReflect.Descriptor instead.
func (*GetResumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{1}
}

func (x *GetResumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// CreateResumeRequest
type CreateResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	FileUrl       string                 `protobuf:"bytes,5,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	ParsedData    []byte                 `protobuf:"bytes,6,opt,name=parsed_data,json=parsedData,proto3" json:"parsed_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResumeRequest) Reset() {
	*x = CreateResumeRequest{}
	mi := &file_proto_resume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResumeRequest) ProtoMessage() {}

func (x *CreateResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResumeRequest.ProtoReflect.Descriptor instead.
func (*CreateResumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateResumeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateResumeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateResumeRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateResumeRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *CreateResumeRequest) GetParsedData() []byte {
	if x != nil {
		return x.ParsedData
	}
	return nil
}

// UpdateResumeRequest
type UpdateResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	ParsedData    []byte                 `protobuf:"bytes,5,opt,name=parsed_data,json=parsedData,proto3" json:"parsed_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResumeRequest) Reset() {
	*x = UpdateResumeRequest{}
	mi := &file_proto_resume_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResumeRequest) ProtoMessage() {}

func (x *UpdateResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResumeRequest.ProtoReflect.Descriptor instead.
func (*UpdateResumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateResumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateResumeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateResumeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateResumeRequest) GetParsedData() []byte {
	if x != nil {
		return x.ParsedData
	}
	return nil
}

// UpdateStatusRequest
type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_proto_resume_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ListResumesRequest
type ListResumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResumesRequest) Reset() {
	*x = ListResumesRequest{}
	mi := &file_proto_resume_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResumesRequest) ProtoMessage() {}

func (x *ListResumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResumesRequest.ProtoReflect.Descriptor instead.
func (*ListResumesRequest) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{5}
}

func (x *ListResumesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResumesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListResumesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListResumesRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// ListResumesResponse
type ListResumesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resumes       []*Resume              `protobuf:"bytes,1,rep,name=resumes,proto3" json:"resumes,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResumesResponse) Reset() {
	*x = ListResumesResponse{}
	mi := &file_proto_resume_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResumesResponse) ProtoMessage() {}

func (x *ListResumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResumesResponse.ProtoReflect.Descriptor instead.
func (*ListResumesResponse) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{6}
}

func (x *ListResumesResponse) GetResumes() []*Resume {
	if x != nil {
		return x.Resumes
	}
	return nil
}

func (x *ListResumesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_resume_proto protoreflect.FileDescriptor

const file_proto_resume_proto_rawDesc = "" +
	"\n" +
	"\x12proto/resume.proto\x12\x06resume\"\x82\x02\n" +
	"\x06Resume\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x19\n" +
	"\bfile_url\x18\x06 \x01(\tR\afileUrl\x12\x1f\n" +
	"\vparsed_data\x18\a \x01(\fR\n" +
	"parsedData\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"\"\n" +
	"\x10GetResumeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa9\x01\n" +
	"\x13CreateResumeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x19\n" +
	"\bfile_url\x18\x05 \x01(\tR\afileUrl\x12\x1f\n" +
	"\vparsed_data\x18\x06 \x01(\fR\n" +
	"parsedData\"\x86\x01\n" +
	"\x13UpdateResumeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1f\n" +
	"\vparsed_data\x18\x05 \x01(\fR\n" +
	"parsedData\"=\n" +
	"\x13UpdateStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"u\n" +
	"\x12ListResumesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"U\n" +
	"\x13ListResumesResponse\x12(\n" +
	"\aresumes\x18\x01 \x03(\v2\x0e.resume.ResumeR\aresumes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xc5\x02\n" +
	"\rResumeService\x125\n" +
	"\tGetResume\x12\x18.resume.GetResumeRequest\x1a\x0e.resume.Resume\x12;\n" +
	"\fCreateResume\x12\x1b.resume.CreateResumeRequest\x1a\x0e.resume.Resume\x12;\n" +
	"\fUpdateResume\x12\x1b.resume.UpdateResumeRequest\x1a\x0e.resume.Resume\x12;\n" +
	"\fUpdateStatus\x12\x1b.resume.UpdateStatusRequest\x1a\x0e.resume.Resume\x12F\n" +
	"\vListResumes\x12\x1a.resume.ListResumesRequest\x1a\x1b.resume.ListResumesResponseB;Z9github.com/example/ats-platform/internal/shared/pb/resumeb\x06proto3"

var (
	file_proto_resume_proto_rawDescOnce sync.Once
	file_proto_resume_proto_rawDescData []byte
)

func file_proto_resume_proto_rawDescGZIP() []byte {
	file_proto_resume_proto_rawDescOnce.Do(func() {
		file_proto_resume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_resume_proto_rawDesc), len(file_proto_resume_proto_rawDesc)))
	})
	return file_proto_resume_proto_rawDescData
}

var file_proto_resume_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_resume_proto_goTypes = []any{
	(*Resume)(nil),              // 0: resume.Resume
	(*GetResumeRequest)(nil),    // 1: resume.GetResumeRequest
	(*CreateResumeRequest)(nil), // 2: resume.CreateResumeRequest
	(*UpdateResumeRequest)(nil), // 3: resume.UpdateResumeRequest
	(*UpdateStatusRequest)(nil), // 4: resume.UpdateStatusRequest
	(*ListResumesRequest)(nil),  // 5: resume.ListResumesRequest
	(*ListResumesResponse)(nil), // 6: resume.ListResumesResponse
}
var file_proto_resume_proto_depIdxs = []int32{
	0, // 0: resume.ListResumesResponse.resumes:type_name -> resume.Resume
	1, // 1: resume.ResumeService.GetResume:input_type -> resume.GetResumeRequest
	2, // 2: resume.ResumeService.CreateResume:input_type -> resume.CreateResumeRequest
	3, // 3: resume.ResumeService.UpdateResume:input_type -> resume.UpdateResumeRequest
	4, // 4: resume.ResumeService.UpdateStatus:input_type -> resume.UpdateStatusRequest
	5, // 5: resume.ResumeService.ListResumes:input_type -> resume.ListResumesRequest
	0, // 6: resume.ResumeService.GetResume:output_type -> resume.Resume
	0, // 7: resume.ResumeService.CreateResume:output_type -> resume.Resume
	0, // 8: resume.ResumeService.UpdateResume:output_type -> resume.Resume
	0, // 9: resume.ResumeService.UpdateStatus:output_type -> resume.Resume
	6, // 10: resume.ResumeService.ListResumes:output_type -> resume.ListResumesResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_resume_proto_init() }
func file_proto_resume_proto_init() {
	if File_proto_resume_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_resume_proto_rawDesc), len(file_proto_resume_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_resume_proto_goTypes,
		DependencyIndexes: file_proto_resume_proto_depIdxs,
		MessageInfos:      file_proto_resume_proto_msgTypes,
	}.Build()
	File_proto_resume_proto = out.File
	file_proto_resume_proto_goTypes = nil
	file_proto_resume_proto_depIdxs = nil
}
